# Generated by Terraform - do not edit manually; re-run terraform apply to update
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workwhile

resources:
  - ../../base

images:
  - name: workwhile-backend
    newName: ${ecr_backend_url}
    newTag: latest
  - name: workwhile-frontend
    newName: ${ecr_frontend_url}
    newTag: latest
