apiVersion: v1
kind: ConfigMap
metadata:
  name: workwhile-config
  namespace: workwhile
data:
  NODE_ENV: "production"
  PORT: "5000"
  HOST: "0.0.0.0"
  JWT_EXPIRE: "24h"
  JWT_REFRESH_EXPIRE: "7d"
  FRONTEND_URL: "http://localhost"
  BACKEND_URL: "http://localhost"
  PUPPETEER_HEADLESS: "true"
