apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workwhile

resources:
  - namespace.yaml
  # secret.yaml is gitignored; created by CI/CD before kubectl apply (see .github/workflows/ci-cd.yml)
  - configmap.yaml
  - mongodb-pvc.yaml
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - backend-pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-hpa.yaml
  - frontend-hpa.yaml
  - ingress.yaml
  - fluent-bit-configmap.yaml
  - fluent-bit-daemonset.yaml
  - sqs-worker-deployment.yaml
